//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Koning : Schaakstuk
{
	private boolean Staatschaak
	{
		get;
		set;
	}

	private boolean Eerstezet
	{
		get;
		set;
	}

	private void Verplaats()
	{
		throw new System.NotImplementedException();
	}

	private void Rokeren()
	{
		throw new System.NotImplementedException();
	}

}

