//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Pion : Schaakstuk
{
	private boolean Eerstezet
	{
		get;
		set;
	}

	private void Verplaats()
	{
		throw new System.NotImplementedException();
	}

	private void EnPassant()
	{
		throw new System.NotImplementedException();
	}

}

