//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Schaakbord
{
	public virtual {
		get;
		set;
	}

	private void CheckRemise()
	{
		throw new System.NotImplementedException();
	}

	private void CheckSchaak()
	{
		throw new System.NotImplementedException();
	}

	private void CheckMat()
	{
		throw new System.NotImplementedException();
	}

}

