//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Spel
{
	private object Speleraanzet
	{
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	private void Start()
	{
		throw new System.NotImplementedException();
	}

	private void Herstarten()
	{
		throw new System.NotImplementedException();
	}

	private void VeranderSpeler()
	{
		throw new System.NotImplementedException();
	}

}

